### ISSUE TITLE
table不能被正常转换

### ISSUE THREAD

**Issue by FurryWolfX** [island205/h2m#11]
html中的table不能转换成md的table

**Comment by island205** [comment]
已经支持了，可以发一下你的 HTML 文件么？我测试一下

**Comment by RelaxLiu** [comment]
<h2 id="-">文档正文</h2>
<h6 id="-">响应参数:</h6>
<h6 id="data-">data:</h6>
<table>
<thead>
<tr>
<th>字段</th>
<th>类型</th>
<th>说明</th>
</tr>
</thead>
<tbody><tr>
<td>id</td>
<td>int</td>
<td>用户的ID</td>
</tr>
<tr>
<td>name</td>
<td>string</td>
<td>用户名称</td>
</tr>
<tr>
<td>session_id</td>
<td>string</td>
<td>用户session</td>
</tr>
<tr>
<td>is_administrators</td>
<td>bool</td>
<td>true:是管理员 false:不是管理员</td>
</tr>
<tr>
<td>email</td>
<td>string</td>
<td>用户邮箱</td>
</tr>
</tbody></table>
<h6 id="-">错误码:</h6>
<table>
<thead>
<tr>
<th>错误码</th>
<th>说明</th>
</tr>
</thead>
<tbody><tr>
<td>password_error</td>
<td>密码错误</td>
</tr>
<tr>
<td>email_not_exists</td>
<td>邮箱不存在</td>
</tr>
<tr>
<td>params_empty</td>
<td>参数为空</td>
</tr>
</tbody></table>

@island205 @ @oscWolfX

**Comment by RelaxLiu** [comment]
‘<h2 id="-">文档正文</h2>
<h6 id="-">响应参数:</h6>
<h6 id="data-">data:</h6>
<table>
<thead>
<tr>
<th>字段</th>
<th>类型</th>
<th>说明</th>
</tr>
</thead>
<tbody><tr>
<td>id</td>
<td>int</td>
<td>用户的ID</td>
</tr>
<tr>
<td>name</td>
<td>string</td>
<td>用户名称</td>
</tr>
<tr>
<td>session_id</td>
<td>string</td>
<td>用户session</td>
</tr>
<tr>
<td>is_administrators</td>
<td>bool</td>
<td>true:是管理员 false:不是管理员</td>
</tr>
<tr>
<td>email</td>
<td>string</td>
<td>用户邮箱</td>
</tr>
</tbody></table>
<h6 id="-">错误码:</h6>
<table>
<thead>
<tr>
<th>错误码</th>
<th>说明</th>
</tr>
</thead>
<tbody><tr>
<td>password_error</td>
<td>密码错误</td>
</tr>
<tr>
<td>email_not_exists</td>
<td>邮箱不存在</td>
</tr>
<tr>
<td>params_empty</td>
<td>参数为空</td>
</tr>
</tbody></table>’
@island205 @oscWolfX

**Comment by RelaxLiu** [comment]
@island205 @oscWolfX 
表格可以了  应用的：h2m(html, {converter: 'MarkdownExtra'})
但是有一个问题就是渲染出来的非表格的多了好多#
## 文档正文 ## (#-)

###### 响应参数: ###### (#-)

###### data: ###### (#data-)
类似这样的
![image](https://user-images.githubusercontent.com/16301089/44646887-09c5f600-aa0f-11e8-8a16-32e499b1c687.png)

**Comment by RelaxLiu** [comment]
谢谢作者，目前找到其他的解决方案了，不用转来转去了，后端直接给我markdown格式的了，感谢
