### ISSUE TITLE
stdin and options for command line tool

### ISSUE THREAD

**Issue by unrzn0** [island205/h2m#15]
Hi,

thanks for h2m - seems exactly what I was looking for to convert HTML in the clipboard to Markdown - and the best feature for me is that styles are not conserved, therefore the resulting Markdown becomes useable! Cool!

For a command line workflow, could you add the options also to the command line tool and also add stdin support, so that a one-liner without temp files could become possible?

Thanks, and keep the good work up!

**Comment by island205** [comment]
ok

**Comment by island205** [comment]
@unrzn0 add `$ h2m -c` to convert from clipboard directly, please update to 0.7.0
