### ISSUE TITLE
Can't convert:Cannot read property 'src' of undefined

### ISSUE THREAD

**Issue by mrdream24** [island205/h2m#3]
TypeError: Cannot read property 'src' of undefined    at getMarkdownInNode (http://island205.github.io/h2m/dist/h2m.js:174:23)    at http://island205.github.io/h2m/dist/h2m.js:264:13    at http://island205.github.io/h2m/dist/h2m.js:3119:20    at traverse (http://island205.github.io/h2m/dist/h2m.js:3166:32)    at Array.walk (http://island205.github.io/h2m/dist/h2m.js:3118:16)    at getMarkdownInTree (http://island205.github.io/h2m/dist/h2m.js:263:8)    at module.exports (http://island205.github.io/h2m/dist/h2m.js:280:10)    at HTMLTextAreaElement.onChange (http://island205.github.io/h2m/assets/converter.js:20:16)-------html-------<h1>ahahah</h1><img>

**Comment by island205** [comment]
fixed in https://github.com/island205/h2m/commit/ceb3897cda4e8ccdfc1c97fd34e9703a531f0483
